<a href="https://colab.research.google.com/github/karthikheyaa17/AI---Workshop-2022/blob/main/Day_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [142]:
import numpy as ny

lt = [1, 2, 3, 4]
rt = ny.array([1, 2, 3, 4])

print("My list:", lt)
print("Numy list:", rt)



My list: [1, 2, 3, 4]
Numy list: [1 2 3 4]


In [143]:
import numpy as np
b = np.array([0.5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])
print(b[::20])
print(b[::2])
print(b[::-1])
print(b[::-2])
print(b[10:3])
print(b[3: 10: -2])

# np.ones(4)

# np.zeros(4)

np.empty(4)



[0.5]
[ 0.5  3.   5.   7.   9.  11.  13. ]
[13.  12.  11.  10.   9.   8.   7.   6.   5.   4.   3.   2.   0.5]
[13.  11.   9.   7.   5.   3.   0.5]
[]
[]


array([4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323])

In [144]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [145]:
import random
np.random.rand(3, 3)

array([[0.86579867, 0.59713678, 0.45091727],
       [0.92338076, 0.58302836, 0.23128508],
       [0.43464154, 0.35216965, 0.27087733]])

In [146]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

a.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [147]:
np.random.randint(1, 5, size=(4, 4))

array([[2, 2, 2, 1],
       [2, 4, 3, 3],
       [2, 2, 3, 1],
       [2, 4, 1, 1]])

In [148]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = np.array([0.5, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])


np.concatenate((a, b))

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. , 11. ,
       12. ,  0.5,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. ,
       11. , 12. , 13. ])

In [149]:
np.append(a, b)

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. , 11. ,
       12. ,  0.5,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10. ,
       11. , 12. , 13. ])

In [150]:
a.size

12

In [151]:
b.size

13

In [152]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.shape

(3, 3)

In [153]:
arr.size

9

In [154]:
arr.sum()

45

In [155]:
arr.std()

2.581988897471611

In [156]:
arr.var()

6.666666666666667

In [157]:
arr.mean()

5.0

In [158]:
arr = np.array([7, 8, 9, 1, 2, 3, 6, 5, 4])

arr.sort()

arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
arr = np.array([[[1], [1], [1]]])

np.squeeze(arr)

array([1, 1, 1])

In [160]:
x = np.array([[[0], [1], [2]]])
x.shape


(1, 3, 1)

In [161]:
np.squeeze(x)

array([0, 1, 2])

In [162]:
# Create a 2D Array of random number of 4, 4

np.random.randint(100, size=(4, 4))

array([[79, 13, 77,  6],
       [46, 37, 14,  0],
       [42, 42, 17, 28],
       [69, 55, 68, 61]])

In [163]:
np.random.rand(16).reshape((4,4))

array([[0.77244162, 0.54468243, 0.89866718, 0.62716241],
       [0.78367663, 0.83362662, 0.88069579, 0.35591246],
       [0.01986446, 0.44093399, 0.57155871, 0.11345696],
       [0.04037314, 0.09913859, 0.75542109, 0.47405052]])

In [164]:
np.random.rand(4,4)

array([[0.98741873, 0.39326529, 0.80631783, 0.34341129],
       [0.01369857, 0.35520907, 0.42382313, 0.24085713],
       [0.57210607, 0.46771444, 0.84496205, 0.72895945],
       [0.64895922, 0.89081374, 0.8275468 , 0.3637636 ]])

In [165]:
np.random.rand(4, 4, 4)

array([[[0.90156732, 0.19176352, 0.51945187, 0.82863115],
        [0.74583438, 0.68801392, 0.10442814, 0.20356331],
        [0.78939197, 0.32042117, 0.21407318, 0.29050172],
        [0.24864983, 0.33670911, 0.56078762, 0.65510198]],

       [[0.99062779, 0.00288843, 0.63401918, 0.73502292],
        [0.51598536, 0.79650921, 0.64260465, 0.6237932 ],
        [0.81919549, 0.90728462, 0.32524262, 0.87019795],
        [0.87022665, 0.38216385, 0.58902765, 0.3418794 ]],

       [[0.16648845, 0.22854914, 0.96346919, 0.13553268],
        [0.00659052, 0.54578454, 0.60115639, 0.57720216],
        [0.42655878, 0.5446442 , 0.51897431, 0.36848758],
        [0.14843701, 0.57359859, 0.97412804, 0.70888466]],

       [[0.35691131, 0.22161262, 0.22146918, 0.61234693],
        [0.05225798, 0.45520914, 0.52041673, 0.49596467],
        [0.79297419, 0.52515438, 0.16821999, 0.14082533],
        [0.27068701, 0.14256503, 0.21305755, 0.80247767]]])

In [166]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [167]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [168]:
# Concatenate
# Create a 2D Array of random number of (4, 4)

random1 = np.random.rand(2, 2)
random2 = np.random.rand(2, 2)

random1.shape

(2, 2)

In [169]:
random2.shape

(2, 2)

In [170]:
reshape = np.concatenate((random1, random2))
reshape.reshape(2, 4)

array([[0.74205026, 0.36801066, 0.71800072, 0.15552245],
       [0.19823852, 0.85880796, 0.73180463, 0.8578    ]])

In [184]:
y = np.concatenate((random1, random2), axis = 1)
y

array([[0.74205026, 0.36801066, 0.19823852, 0.85880796],
       [0.71800072, 0.15552245, 0.73180463, 0.8578    ]])

In [183]:
y.shape

(2, 4)

In [178]:
round(np.concatenate((random1, random2), axis = 1).sum(), 2)

4.63

In [195]:
x = np.random.randint(100, size=(5, 5))
x

array([[39, 55, 97, 43, 80],
       [97, 68, 39, 16, 18],
       [65, 14, 15,  1, 58],
       [59, 62, 15, 18, 43],
       [59, 51, 11, 56, 45]])

In [196]:
x[:,:]

array([[39, 55, 97, 43, 80],
       [97, 68, 39, 16, 18],
       [65, 14, 15,  1, 58],
       [59, 62, 15, 18, 43],
       [59, 51, 11, 56, 45]])

In [197]:
x[0, :]

array([39, 55, 97, 43, 80])

In [198]:
x[1, :]

array([97, 68, 39, 16, 18])

In [215]:
# Identity Matrix

r1 = np.ones((5,5))

count = 0
while count <= 4:
  r1[count][count] = 0
  count+=1

r1

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [220]:
r1.sum(axis = 1)

array([4., 4., 4., 4., 4.])

In [222]:
x1 = np.random.randint(1, 26, size = (5, 5))
x1

array([[21, 10,  7,  3, 15],
       [12, 25, 15, 11, 24],
       [ 4, 23, 16,  5, 11],
       [11,  7, 16, 23, 22],
       [22, 25, 25,  6, 10]])

In [228]:
x1.sum(axis = 0)

array([70, 90, 79, 48, 82])

In [232]:
x1.mean(axis = 0)

array([14. , 18. , 15.8,  9.6, 16.4])

In [233]:
x1.var(axis = 0)

array([45.2 , 61.6 , 32.56, 51.84, 32.24])

In [234]:
x1.std(axis = 0)

array([6.72309453, 7.84856675, 5.70613705, 7.2       , 5.67802783])

In [ ]:
# explore
